#!/usr/bin/env bash
# Installer for kiosk-manager. Run it as the kiosk user (NOT with sudo).
set -euo pipefail

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
LIB_DIR="$PREFIX/lib/kiosk-manager"
BIN_DIR="$PREFIX/bin"
BIN="$BIN_DIR/kiosk-manager"
UNIT_DIR="$HOME/.config/systemd/user"
AUTOSTART_DIR="$HOME/.config/autostart"
APPS_DIR="$PREFIX/share/applications"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/kiosk-manager"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kiosk-manager"
BACKUP_DIR="$HOME/kiosk-manager-backup-$(date +%Y%m%d-%H%M%S)"

URL_OVERRIDE=""
DO_MIGRATE=1
INSTALL_DEPS=0
UPDATE_MODE=0

usage() {
    cat <<USAGE
Usage: ./install.sh [options]

  --url URL        kiosk page to configure (default: taken from the old
                   startup.sh if present, otherwise left as-is)
  --no-migrate     do not touch the existing kiosk-browser units / startup.sh
  --install-deps   apt-get install the required packages (uses sudo)
  --update         non-interactive upgrade, used by the auto-updater
  -h, --help       show this help
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        --url) URL_OVERRIDE="${2:-}"; shift 2 ;;
        --no-migrate) DO_MIGRATE=0; shift ;;
        --install-deps) INSTALL_DEPS=1; shift ;;
        --update) UPDATE_MODE=1; DO_MIGRATE=0; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "unknown option: $1" >&2; usage; exit 1 ;;
    esac
done

if [ "$(id -u)" = "0" ]; then
    echo "Run this as the kiosk user, not as root." >&2
    exit 1
fi

say() { printf '\n== %s\n' "$*"; }

# --------------------------------------------------------------- dependencies
PACKAGES="python3 python3-gi gir1.2-gtk-3.0 x11-xserver-utils xdotool wmctrl git firefox-esr"
if [ "$INSTALL_DEPS" = "1" ]; then
    say "Installing packages"
    sudo apt-get update
    # firefox-esr is the Debian package name; skip it if firefox is already there.
    if command -v firefox >/dev/null 2>&1; then
        PACKAGES="${PACKAGES/ firefox-esr/}"
    fi
    # shellcheck disable=SC2086
    sudo apt-get install -y $PACKAGES
fi

say "Checking dependencies"
MISSING=""
command -v python3 >/dev/null 2>&1 || MISSING="$MISSING python3"
# require_version only checks the typelib, so this works without a display
# (the auto-updater runs this script from a background job).
python3 -c "import gi; gi.require_version('Gtk','3.0')" \
    >/dev/null 2>&1 || MISSING="$MISSING python3-gi/gir1.2-gtk-3.0"
command -v xset >/dev/null 2>&1 || MISSING="$MISSING x11-xserver-utils"
command -v xdotool >/dev/null 2>&1 || MISSING="$MISSING xdotool"
command -v wmctrl >/dev/null 2>&1 || MISSING="$MISSING wmctrl"
if [ -n "$MISSING" ]; then
    echo "Missing:$MISSING"
    echo "Install them with:"
    echo "  sudo apt-get install -y $PACKAGES"
    echo "or re-run:  ./install.sh --install-deps"
    exit 1
fi
echo "All present."
command -v git >/dev/null 2>&1 || \
    echo "Note: git is not installed; automatic updates need it (sudo apt-get install git)."

FIREFOX="$(command -v firefox || command -v firefox-esr || echo /usr/bin/firefox)"

# ------------------------------------------------------------------- old setup
OLD_URL=""
OLD_STARTUP="$HOME/scripts/startup.sh"
if [ -f "$OLD_STARTUP" ]; then
    OLD_URL="$(grep -oE 'https?://[^ "'"'"']+' "$OLD_STARTUP" | head -n1 || true)"
fi

if [ "$DO_MIGRATE" = "1" ]; then
    say "Removing the previous kiosk-browser setup"
    mkdir -p "$BACKUP_DIR"
    for unit in kiosk-browser.timer kiosk-browser.service; do
        if systemctl --user list-unit-files 2>/dev/null | grep -q "^$unit"; then
            systemctl --user disable --now "$unit" 2>/dev/null || true
            echo "disabled $unit"
        fi
        if [ -f "$UNIT_DIR/$unit" ]; then
            mv "$UNIT_DIR/$unit" "$BACKUP_DIR/"
            echo "moved $unit to $BACKUP_DIR"
        fi
    done
    rm -f "$UNIT_DIR"/timers.target.wants/kiosk-browser.timer 2>/dev/null || true
    rm -f "$UNIT_DIR"/graphical-session.target.wants/kiosk-browser.service 2>/dev/null || true
    if [ -f "$OLD_STARTUP" ]; then
        mv "$OLD_STARTUP" "$BACKUP_DIR/startup.sh"
        echo "moved startup.sh to $BACKUP_DIR"
    fi
    systemctl --user daemon-reload
fi

# --------------------------------------------------------------------- install
say "Installing to $LIB_DIR"
mkdir -p "$LIB_DIR" "$BIN_DIR" "$UNIT_DIR" "$APPS_DIR" "$DATA_DIR" "$CONFIG_DIR"
rm -rf "$LIB_DIR/kiosk_manager"
cp -r "$SRC_DIR/kiosk_manager" "$LIB_DIR/"
cp "$SRC_DIR/README.md" "$DATA_DIR/README.md" 2>/dev/null || true
find "$LIB_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

# The updater compares this commit with the branch head on GitHub.
if git -C "$SRC_DIR" rev-parse HEAD >"$LIB_DIR/VERSION" 2>/dev/null; then
    echo "version: $(cut -c1-7 "$LIB_DIR/VERSION")"
else
    rm -f "$LIB_DIR/VERSION"
    echo "version: unknown (not installed from a git checkout)"
fi

cat > "$BIN" <<LAUNCHER
#!/bin/sh
# Generated by install.sh
KIOSK_MANAGER_BIN="$BIN"
export KIOSK_MANAGER_BIN
PYTHONPATH="$LIB_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONPATH
exec python3 -m kiosk_manager "\$@"
LAUNCHER
chmod +x "$BIN"
echo "launcher: $BIN"

sed "s|Exec=kiosk-manager gui|Exec=$BIN gui|" \
    "$SRC_DIR/desktop/kiosk-manager.desktop" > "$APPS_DIR/kiosk-manager.desktop"
# The service starts the settings window itself now ("Keep this window
# running" on the System tab), so drop the login autostart entry that
# version 1.0 installed.
rm -f "$AUTOSTART_DIR/kiosk-manager.desktop"
echo "menu entry installed"

sed "s|%h/.local/bin/kiosk-manager|$BIN|g" \
    "$SRC_DIR/systemd/kiosk-manager.service" > "$UNIT_DIR/kiosk-manager.service"
echo "unit: $UNIT_DIR/kiosk-manager.service"

# ---------------------------------------------------------------------- config
say "Seeding configuration"
CONFIG_FILE="$CONFIG_DIR/config.json"
if [ ! -f "$CONFIG_FILE" ]; then
    # The bare fundbot URL from the old startup.sh is upgraded to the ?kiosk
    # layout by config.load(), so it is safe to carry over here.
    URL="${URL_OVERRIDE:-${OLD_URL:-https://fundbot.adman.casa/?kiosk}}"
    python3 - "$CONFIG_FILE" "$URL" "$FIREFOX" <<'PYSEED'
import json, sys
path, url, firefox = sys.argv[1], sys.argv[2], sys.argv[3]
cfg = {
    "url": url,
    "browser": {"command": firefox, "kiosk": True, "private_window": False,
                "extra_args": [], "use_managed_profile": True},
    "boot": {"launch_on_boot": True, "delay_seconds": 15,
             "restart_if_closed": True, "restart_grace_seconds": 20},
    "schedule": {"enabled": True, "entries": []},
    "screen": {"manage_timeout": True, "blank_after_minutes": 0,
               "dpms_off_after_minutes": 0, "disable_lock": True},
    "gui": {"start_minimized": True},
}
with open(path, "w") as fh:
    json.dump(cfg, fh, indent=2)
    fh.write("\n")
print("wrote", path, "with url", url)
PYSEED
elif [ -n "$URL_OVERRIDE" ]; then
    "$BIN" set-url "$URL_OVERRIDE"
else
    echo "keeping existing $CONFIG_FILE"
fi

# ---------------------------------------------------------------------- enable
say "Enabling the service"
systemctl --user daemon-reload
systemctl --user enable kiosk-manager.service
# restart rather than start, so a reinstall or an update runs the new code.
# The kiosk browser and settings window live in their own scopes and survive.
systemctl --user restart kiosk-manager.service
if [ "$UPDATE_MODE" = "1" ]; then
    echo "update installed: $(cat "$LIB_DIR/VERSION" 2>/dev/null || echo unknown)"
    exit 0
fi
sleep 2
systemctl --user --no-pager --lines=5 status kiosk-manager.service || true

# Keep the user service alive without an interactive login session.
if command -v loginctl >/dev/null 2>&1; then
    if ! loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q "Linger=yes"; then
        echo
        echo "Tip: if the kiosk boots straight to a session without a login,"
        echo "run once:  sudo loginctl enable-linger $USER"
    fi
fi

say "Done"
cat <<DONE
Configure it:      $BIN gui
Raise the window:  $BIN show    (bind this to a hotkey, e.g. Ctrl+Alt+K)
Service control:   systemctl --user status|restart kiosk-manager.service
Live log:          journalctl --user -u kiosk-manager.service -f
Updates:           $BIN update-check   /   $BIN update
Config file:       $CONFIG_FILE
DONE
if [ "$DO_MIGRATE" = "1" ] && [ -d "$BACKUP_DIR" ]; then
    echo "Old files backed up in: $BACKUP_DIR"
fi
