"""Launching, inspecting and steering the kiosk Firefox instance."""

import logging
import os
import shutil
import signal
import subprocess
import time

from . import config, procs

log = logging.getLogger("kiosk.browser")

# Unique marker baked into the command line so we can find the kiosk instance
# even if it was started by a previous run of the daemon.
MARKER = "kiosk-manager-session"

USER_JS_TEMPLATE = """// Generated by kiosk-manager. Edits here are overwritten on launch.
user_pref("browser.startup.homepage", "{url}");
user_pref("browser.startup.page", 1);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("extensions.pocket.enabled", false);
user_pref("full-screen-api.warning.timeout", 0);
user_pref("full-screen-api.warning.delay", 0);
user_pref("dom.w3c_touch_events.enabled", 1);
user_pref("apz.overscroll.enabled", true);
user_pref("general.smoothScroll", true);
user_pref("signon.rememberSignons", false);
user_pref("browser.download.useDownloadDir", true);
"""


def _has(cmd):
    return shutil.which(cmd) is not None


def _run(args, timeout=10):
    try:
        proc = subprocess.run(args, stdout=subprocess.PIPE,
                              stderr=subprocess.DEVNULL, timeout=timeout,
                              check=False)
        return proc.returncode == 0, proc.stdout.decode("utf-8", "replace")
    except (OSError, subprocess.SubprocessError) as exc:
        log.debug("%s failed: %s", args[0], exc)
        return False, ""


class BrowserManager:
    def __init__(self, cfg):
        self.cfg = cfg
        self.proc = None
        self.launched_at = 0.0

    def update_config(self, cfg):
        self.cfg = cfg

    # ---- profile -------------------------------------------------------
    def _write_profile(self):
        path = config.PROFILE_DIR
        os.makedirs(path, exist_ok=True)
        url = self.cfg.get("url", "").strip().replace(chr(34), "%22")
        with open(os.path.join(path, "user.js"), "w", encoding="utf-8") as fh:
            fh.write(USER_JS_TEMPLATE.format(url=url))
        # Stop Firefox nagging about a profile that was not shut down cleanly.
        for name in ("sessionstore.jsonlz4", "sessionstore-backups"):
            target = os.path.join(path, name)
            if os.path.isdir(target):
                shutil.rmtree(target, ignore_errors=True)
            elif os.path.exists(target):
                try:
                    os.remove(target)
                except OSError:
                    pass
        return path

    # ---- process state -------------------------------------------------
    def _tracked_alive(self):
        return self.proc is not None and self.proc.poll() is None

    def _find_pids(self):
        ok, out = _run(["pgrep", "-f", MARKER])
        if not ok:
            return []
        pids = []
        for token in out.split():
            try:
                pid = int(token)
            except ValueError:
                continue
            if pid != os.getpid():
                pids.append(pid)
        return pids

    def is_running(self):
        if self._tracked_alive():
            return True
        return bool(self._find_pids())

    def window_id(self):
        """Return the X11 window id of the kiosk window, if it is mapped."""
        if not _has("xdotool") or not os.environ.get("DISPLAY"):
            return None
        for needle in (MARKER, "firefox"):
            ok, out = _run(["xdotool", "search", "--onlyvisible", "--class", needle])
            if not ok:
                continue
            ids = [line.strip() for line in out.splitlines() if line.strip()]
            if ids:
                return ids[-1]
        return None

    def _use_profile(self):
        return bool(self.cfg.get("browser", {}).get("use_managed_profile", True))

    def status(self):
        return {
            "running": self.is_running(),
            "pids": self._find_pids(),
            "window": self.window_id(),
            "launched_at": self.launched_at,
            "url": self.cfg.get("url", ""),
            "profile": config.PROFILE_DIR if self._use_profile() else "(default)",
        }

    # ---- actions -------------------------------------------------------
    def build_command(self):
        bcfg = self.cfg.get("browser", {})
        cmd = [bcfg.get("command") or "/usr/bin/firefox"]
        if bcfg.get("kiosk", True):
            cmd.append("--kiosk")
        if bcfg.get("private_window"):
            cmd.append("--private-window")
        if self._use_profile():
            cmd += ["--profile", self._write_profile()]
        for arg in bcfg.get("extra_args") or []:
            arg = str(arg).strip()
            if arg:
                cmd.append(arg)
        # Sets WM_CLASS (documented X11 flag) and, as a side effect, gives
        # pgrep and xdotool something unique to match this instance on.
        cmd += ["--class", MARKER]
        cmd.append(self.cfg.get("url", ""))
        return cmd

    def launch(self):
        if self.is_running():
            log.info("launch requested but the kiosk browser is already running")
            return False, "already running"
        cmd = self.build_command()
        env = dict(os.environ)
        env.setdefault("DISPLAY", ":0")
        env.setdefault("MOZ_ENABLE_WAYLAND", "0")
        log.info("launching: %s", " ".join(cmd))
        try:
            self.proc = procs.spawn(cmd, env=env, scope="kiosk-manager-browser")
        except OSError as exc:
            log.error("launch failed: %s", exc)
            return False, str(exc)
        self.launched_at = time.time()
        return True, "launched pid %d" % self.proc.pid

    def stop(self):
        stopped = []
        if self._tracked_alive():
            try:
                self.proc.terminate()
                stopped.append(self.proc.pid)
            except OSError:
                pass
        for pid in self._find_pids():
            try:
                os.kill(pid, signal.SIGTERM)
                stopped.append(pid)
            except OSError:
                pass
        deadline = time.time() + 8
        while time.time() < deadline and self.is_running():
            time.sleep(0.4)
        for pid in self._find_pids():
            try:
                os.kill(pid, signal.SIGKILL)
            except OSError:
                pass
        self.proc = None
        return stopped

    def raise_window(self):
        wid = self.window_id()
        if wid and _has("xdotool"):
            _run(["xdotool", "windowactivate", "--sync", wid])
            _run(["xdotool", "windowraise", wid])
            return True
        if _has("wmctrl"):
            ok, _ = _run(["wmctrl", "-a", "Mozilla Firefox"])
            return ok
        return False

    def return_to_home(self):
        """Send Alt+Home so an idle kiosk goes back to the configured URL."""
        wid = self.window_id()
        if not wid or not _has("xdotool"):
            return False
        _run(["xdotool", "windowactivate", "--sync", wid])
        _run(["xdotool", "key", "--clearmodifiers", "--window", wid, "alt+Home"])
        return True

    def ensure_open(self, return_to_home=True):
        """Open the kiosk page, or just raise it when it is already up."""
        if self.is_running():
            self.raise_window()
            if return_to_home:
                self.return_to_home()
            return "raised"
        ok, msg = self.launch()
        return "launched" if ok else "failed: %s" % msg

    def restart(self):
        self.stop()
        time.sleep(1.0)
        return self.launch()
